### ISSUE TITLE
stderr: x86_64-w64-mingw32-gcc: error: : No such file or directory

### ISSUE THREAD

**Issue by fractal-fumbler** [Cabopust/dxvk-mingw-performance#1] opened 2021-05-30 03:11 UTC
Hello :)
trying to makepkg and having this error after build is started, also tried building in [clean chroot](https://wiki.archlinux.org/title/DeveloperWiki:Building_in_a_clean_chroot), but got same error, that i provide below
```
Build started at 2021-05-30T06:00:09.182978
Main binary: /usr/bin/python
Build Options: -Denable_tests=true -Dprefix=/usr/share/dxvk/x64 -Dbindir= -Dlibdir= -Dbuildtype=release -Dstrip=True '--cross-file dxvk/build-win64.txt'
Python system: Linux
The Meson build system
Version: 0.58.0
Source dir: /build/dxvk-mingw-performance/src/dxvk
Build dir: /build/dxvk-mingw-performance/src/build/x64
Build type: cross build
Project name: dxvk
Project version: v1.8.1

dxvk/meson.build:1:0: ERROR: Unable to detect linker for compiler "x86_64-w64-mingw32-gcc -Wl,--version -march=x86-64 -mtune=generic -O2 -pipe -fexceptions         -Wp,-D_FORTIFY_SOURCE=2,-D_GLIBCXX_ASSERTIONS         -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -mno-avx"
stdout: 
stderr: x86_64-w64-mingw32-gcc: error: : No such file or directory
x86_64-w64-mingw32-gcc: error: : No such file or directory
x86_64-w64-mingw32-gcc: error: : No such file or directory
x86_64-w64-mingw32-gcc: error: : No such file or directory
x86_64-w64-mingw32-gcc: error: : No such file or directory
x86_64-w64-mingw32-gcc: error: : No such file or directory
x86_64-w64-mingw32-gcc: error: : No such file or directory
x86_64-w64-mingw32-gcc: error: : No such file or directory
x86_64-w64-mingw32-gcc: error: : No such file or directory
x86_64-w64-mingw32-gcc: error: : No such file or directory
x86_64-w64-mingw32-gcc: error: : No such file or directory
x86_64-w64-mingw32-gcc: error: : No such file or directory
x86_64-w64-mingw32-gcc: error: : No such file or directory
x86_64-w64-mingw32-gcc: error: : No such file or directory
x86_64-w64-mingw32-gcc: error: : No such file or directory
x86_64-w64-mingw32-gcc: error: : No such file or directory
x86_64-w64-mingw32-gcc: error: : No such file or directory
x86_64-w64-mingw32-gcc: error: : No such file or directory
x86_64-w64-mingw32-gcc: error: : No such file or directory
x86_64-w64-mingw32-gcc: error: : No such file or directory
x86_64-w64-mingw32-gcc: error: : No such file or directory
x86_64-w64-mingw32-gcc: error: : No such file or directory
x86_64-w64-mingw32-gcc: error: : No such file or directory
x86_64-w64-mingw32-gcc: error: : No such file or directory
```

**Comment by Cabopust** [comment] 2021-05-30 12:00
Hi. Can you provide your makepkg.conf? Arch Linux has recently updated the default compilation flags configuration, but they should not interfere with the dxvk build.

**Comment by Cabopust** [comment] 2021-05-30 13:35
The new makepkg flags do cause build errors. The commit https://github.com/Cabopust/dxvk-mingw-performance/commit/62696681dc98f495b5dbfda9c66ae1d8b4e48ad6 should try to fix this. Is your issue still relevant?

**Comment by fractal-fumbler** [comment] 2021-05-30 23:57
Hi!
Thanks for your link about makepkg flags, removed non-default -Wformat.

Nonetheless, i still got an error when trying to compile package.
was confused about error with
```
 dxvk/meson.build:1:0: ERROR: Unable to detect linker for compiler "x86_64-w64-mingw32-gcc -Wl,--version -march=x86-64 -mtune=generic -O2 -pipe -fexceptions         -mno-avx"  
stdout:                                                                                                                 
stderr: x86_64-w64-mingw32-gcc: error: : No such file or directory  
```
especially error about missing file and directory and space between -fexceptions and -mno-avx.
so i deleted from CFLAGS everything except `-march=x86-64 -mtune=generic -O2 -pipe` and packaged compiled successfully.

Then i made oneliner with default settings
```
CFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2,-D_GLIBCXX_ASSERTIONS -Wformat -Werror=format-security -fstack-clash-protection -fcf-protection"
```
And package compiled successfully again.
so i guess problem was with spaces or tabs in my makepkg.conf, although i changed only mtune from generic to native.
![photo_2021-05-31_02-54-32](https://user-images.githubusercontent.com/80472908/120124164-84189b80-c1a2-11eb-80f4-8f9d9171e23f.jpg)

**Comment by Cabopust** [comment] 2021-05-31 08:25
Well, I don't know why, but now that I have exactly copied the new defaults in makepkg.conf, I have the same situation. This problem is probably caused by joining lines in makepkg.conf with the escape character '\'. After merging all the flags into one line, the compilation runs without errors.  Maybe this is a specific feature of the MINGW compiler itself, which doesn't support line escaping with compilation flags, or the problem is caused by the DXVK build settings. So far I don't know how to solve this problem in case of this package from under PKGBUILD.

**Comment by Cabopust** [comment] 2021-05-31 12:53
So, I want to say right away that the problem is not with the MINGW compiler or Meson. This problem is really only specific to the dxvk-mingw package. 
First of all, dxvk-mingw copies the compilation flags provided by makepkg.conf and ignores the problem flags from them for building. It then rewrites the compiler preferences on top of makepkg.conf thanks to dxvk-extraopts.patch. The problem here is that when it reads the makepkg.conf configuration, it takes the tabs and line breaks over the escape as more empty compilation flags, which is, of course, incorrect:
```
[built-in options]
c_args=['-march=x86-64','-mtune=generic','-O2','-pipe','-fexceptions','','','','','','','','','','','','','','','','','-fcf-protection','-mno-avx']
cpp_args=['-march=x86-64','-mtune=generic','-O2','-pipe','-fexceptions','','','','','','','','','','','','','','','','','-fcf-protection','-mno-avx']
c_link_args = ['-Wl,-O1,--sort-common,--as-needed']
cpp_link_args = ['-Wl,-O1,--sort-common,--as-needed']
```
This is what is causing your error. To fix this, you just need to remove those empty flags from the Meson configuration. This will be fixed in the next commit.

**Closed** 2021-05-31 13:10 UTC
